"""Compact mask-aware residual CNN for historical sea-ice benchmarks."""

MODEL_NAME = "POLARIS Sea-Ice Residual CNN v0.1"
PREDICTION_CLASSIFICATION = "MODEL_PREDICTION"
TARGET_CLASSIFICATION = "OBSERVATION"
EVALUATION_MODE = "HISTORICAL_FORECAST_BENCHMARK"

__all__ = [
    "EVALUATION_MODE",
    "MODEL_NAME",
    "PREDICTION_CLASSIFICATION",
    "TARGET_CLASSIFICATION",
]
