import { useState } from "react";
import { activateRoute, replanRoute, updatePosition } from "../../services/replanningApi.js";

export default function ReplanningPanel({ route, onDecision }) {
  const [active, setActive] = useState(null); const [decision, setDecision] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function activate() { if (!route) return; setError(""); try { setActive(await activateRoute(`voyage-${route.route_id}`, route)); } catch (e) { setError(e.message); } }
  async function replan() { setLoading(true); setError(""); try { const result = await replanRoute(); setDecision(result); onDecision?.(result); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  async function position() { if (!active) return; try { setActive(await updatePosition(active.current_position_lat, active.current_position_lon, new Date().toISOString())); } catch (e) { setError(e.message); } }
  return <section className="rail-section replanning-panel" aria-label="Dynamic replanning"><span className="panel-kicker">CHECKPOINT 6 / CAPTAIN-IN-THE-LOOP</span><h3>Active Route</h3>{route && !active && <button type="button" onClick={activate}>SET AS ACTIVE ROUTE</button>}{active && <><div className="forecast-detail"><span>Objective</span><strong>{active.objective}</strong></div><div className="forecast-detail"><span>Destination</span><strong>{active.destination?.mapped?.latitude?.toFixed?.(2) ?? "REGIONAL"}</strong></div><div className="forecast-detail"><span>Position source</span><strong>MANUAL</strong></div><button type="button" onClick={position}>UPDATE POSITION</button><button type="button" onClick={replan} disabled={loading}>{loading ? "Evaluating…" : "CHECK FOR SAFER ROUTE"}</button></>}{decision && <div className="replan-decision" role="status"><h4>{decision.decision.replaceAll("_", " ")}</h4><p>{decision.explanation}</p>{decision.reason_codes?.map(code => <small key={code}>{code}</small>)}{decision.candidate_route && <p>Candidate ETA: {decision.candidate_route.eta_hours?.toFixed(1)}h · Risk: {decision.candidate_route.mean_risk?.toFixed(2)}</p>}</div>}{error && <p role="alert">{error}</p>}<small>Recommendations require explicit captain acceptance. No autonomous vessel control or live telemetry is connected.</small></section>;
}
