import { useState } from "react";
import { planRoutes } from "../../services/routesApi.js";

const DEFAULT_ORIGIN = { latitude: -69.41, longitude: 76.19 };
export default function RoutePlannerPanel({ vessels = [], onRoutes, onSelectObjective, selectedObjective, onSelectedRoute }) {
  const [origin, setOrigin] = useState(DEFAULT_ORIGIN); const [destination, setDestination] = useState({ latitude: -68.8, longitude: 77.1 });
  const [vessel, setVessel] = useState("simulated-research"); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(false); const [routes, setPlannedRoutes] = useState([]);
  const setPoint = (setter, key, value) => setter(current => ({ ...current, [key]: Number(value) }));
  async function submit() { setLoading(true); setStatus("PLANNING"); try { const payload = await planRoutes({ origin, destination, departure_time: new Date().toISOString(), vessel_id: vessel }); setPlannedRoutes(payload.routes ?? []); onRoutes(payload.routes ?? []); setStatus(payload.status); } catch (error) { setPlannedRoutes([]); onRoutes([]); setStatus(error.message); } finally { setLoading(false); } }
  return <section className="rail-section route-planner" aria-label="Route Planner"><span className="panel-kicker">CHECKPOINT 5 / ROUTE PLANNER</span><h3>Regional Route Planning</h3><p>Click-ready regional planning for the Bharati / Prydz Bay study grid.</p>{[["Origin", origin, setOrigin], ["Destination", destination, setDestination]].map(([label, point, setter]) => <fieldset key={label}><legend>{label}</legend><label>Lat<input type="number" step="0.01" value={point.latitude} onChange={e => setPoint(setter, "latitude", e.target.value)} /></label><label>Lon<input type="number" step="0.01" value={point.longitude} onChange={e => setPoint(setter, "longitude", e.target.value)} /></label></fieldset>)}<label>Vessel<select value={vessel} onChange={e => setVessel(e.target.value)}>{vessels.map(item => <option key={item.vessel_id} value={item.vessel_id}>{item.name}</option>)}</select></label><button type="button" onClick={submit} disabled={loading}>{loading ? "Planning…" : "PLAN ROUTES"}</button>{status && <strong role="status">{status}</strong>}{routes.length > 0 && <div className="route-comparison" aria-label="Route comparison">{routes.map(route => <button type="button" key={route.route_id} onClick={() => { onSelectObjective?.(route.objective); onSelectedRoute?.(route); }}><b>{route.objective}</b><span>{route.eta_hours?.toFixed(1)}h · {route.distance_km?.toFixed(0)}km</span><small>risk {route.mean_risk?.toFixed(2)} · {route.status}</small></button>)}</div>}</section>;
}
