import { useState } from "react";
import AntarcticMap from "../components/map/AntarcticMap.jsx";
import ConnectivityPanel from "../components/map/ConnectivityPanel.jsx";
import DynamicRiskPanel, { DynamicRiskLegend, useDynamicRisk } from "../components/map/DynamicRiskPanel.jsx";
import OperationsStatusPanel from "../components/map/OperationsStatusPanel.jsx";
import ReplanningPanel from "../components/map/ReplanningPanel.jsx";
import RoutePlannerPanel from "../components/map/RoutePlannerPanel.jsx";

export default function Navigation({ observation, observationError, icebergRegistry }) {
  const risk = useDynamicRisk();
  const [routes, setRoutes] = useState([]);
  const [selectedRoute, setSelectedRoute] = useState(null);
  const [activeRoute, setActiveRoute] = useState(null);
  const environmentState = observation ? "LATEST AVAILABLE" : observationError ? "DEGRADED" : "CONNECTING";
  return <><section className="mission-workspace navigation-workspace"><div className="workspace-header"><div><span className="workspace-kicker">CHECKPOINT 5 / NAVIGATION WORKSPACE</span><h2>Navigation</h2><small>Time-Dependent Antarctic Route Planning &amp; Decision Support · Bharati / Prydz Bay Regional Prototype</small></div><div className="workspace-statuses"><span className="data-chip active">ROUTING ENGINE AVAILABLE</span><span className="data-chip">{environmentState}</span></div></div><div className="map-frame">{observation ? <AntarcticMap metadata={observation.metadata} grid={observation.grid} icebergs={icebergRegistry?.icebergs ?? []} riskField={risk.field} onRiskPoint={risk.setLocation} routes={routes} selectedRoute={selectedRoute} /> : <div className="map-state" role="status"><strong>ROUTING ENGINE AVAILABLE</strong><span>{observationError ? "CURRENT ENVIRONMENT DEGRADED" : "Loading latest available environment..."}</span><span>{observationError || "Route planning will use verified regional inputs when available."}</span></div>}{observation && (risk.field ? <DynamicRiskLegend /> : <div className="map-legend" aria-label="Navigation map legend"><div className="legend-title">ROUTE LAYERS</div><small>SAFE · FAST · ECO · BALANCED</small></div>)}<div className="mission-coordinate-card"><span>REGIONAL PROTOTYPE</span><strong>BHARATI / PRYDZ BAY</strong><small>ANTARCTICA</small></div><div className="map-attribution">Route layers: time-dependent regional planner<br />Decision support only · captain-controlled acceptance</div></div><p className="forecast-notice">Navigation uses verified regional inputs. Current environmental data may be degraded; no fabricated route is displayed.</p></section><aside className="intelligence-rail"><RoutePlannerPanel vessels={risk.vessels} onRoutes={setRoutes} onSelectObjective={setSelectedRoute} onSelectedRoute={setActiveRoute} selectedObjective={selectedRoute?.objective} /><ReplanningPanel route={activeRoute} onDecision={decision => decision.candidate_route && setRoutes([activeRoute, decision.candidate_route])} /><section className="rail-section navigation-context" aria-label="Navigation status"><span className="panel-kicker">NAVIGATION CONTEXT</span><h3>Route Decision Support</h3><div className="forecast-detail"><span>Routing engine</span><strong>AVAILABLE</strong></div><div className="forecast-detail"><span>Environment</span><strong>{environmentState}</strong></div><div className="forecast-detail"><span>Risk context</span><strong>{risk.status?.state ?? "LOADING"}</strong></div><div className="forecast-detail"><span>Data freshness</span><strong>{observation?.metadata?.observation_time ?? "UNAVAILABLE"}</strong></div></section><DynamicRiskPanel risk={risk} /><OperationsStatusPanel /><ConnectivityPanel /></aside></>;
}
